tasks:
  - name: Running bot
    init: pip install -r requirements.txt
    command: python main.py

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - ms-python.python
